# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='web',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
