# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_mission_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('value', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='mission',
            name='web',
        ),
        migrations.AddField(
            model_name='detailitem',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web', to='rest.Mission'),
        ),
    ]
