# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20171112_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailitem',
            old_name='type',
            new_name='tag',
        ),
    ]
